[package]
name = "pallet-bridge"
description = "Artemis Bridge Pallet"
version = "0.1.1"
edition = "2018"
authors = ["Snowmangata-dev <contact@snowmangata-dev.com>"]
repository = "https://github.com/Snowmangata-dev/polkadot-ethereum"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex-literal = { version = "0.3.3", default-features = false }
serde = { version = "1.0.126", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }

frame-support = { default-features = false, version = '4.0.0-dev' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-system = { default-features = false, version = '4.0.0-dev' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-runtime = { default-features = false, version = '6.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-core = { default-features = false, version = '6.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-std = { version = "4.0.0-dev", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-io = { default-features = false, version = '6.0.0' , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }

artemis-core = {default-features = false, version = "0.1.1", git = "https://github.com/imstar15/snowbridge", branch = "debug3"}

[dev-dependencies]
pallet-verifier = {version = "0.1.1", git = "https://github.com/imstar15/snowbridge", branch = "debug3"}
artemis-erc20-app = {version = "0.1.1", git = "https://github.com/imstar15/snowbridge", branch = "debug3"}
artemis-eth-app = {version = "0.1.1", git = "https://github.com/imstar15/snowbridge", branch = "debug3"}
artemis-asset = {version = "0.1.1", git = "https://github.com/imstar15/snowbridge", branch = "debug3"}
orml-tokens = {version = "0.4.1-dev", git = "https://github.com/imstar15/open-runtime-module-library", branch = "debug3"}
orml-traits = { default-features = false, version="0.4.1-dev" , git = "https://github.com/imstar15/open-runtime-module-library", branch = "debug3" }
mangata-types = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }


[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "artemis-core/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"sp-runtime/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
]
